version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: simgan-postgres
    environment:
      POSTGRES_DB: simgan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - simgan_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: simgan-mosquitto
    ports:
      - "1883:1883" #MQTT
      - "9001:9001" #webSockets 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  simgan_data: